[package]
name = "pfm-sys"
version = "0.0.1"
authors = ["Zixian Cai <u5937495@anu.edu.au>"]
edition = "2018"
license-file = "LICENSE"
description = "Binding of libpfm4"
repository = "https://github.com/caizixian/pfm-sys/"
readme = "README.md"

[dependencies]

[build-dependencies]
bindgen = "0.58.1"
