[package]
name = "pfm-sys"
version = "0.1.0"
authors = ["Zixian Cai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.58.1"
